server:
  port: ${PORT:8088}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

  instance:
    preferIpAddress: true
    appname: scheduling-system

logging:
  level:
    org.springframework.web: DEBUG

